import { Hero } from './hero';

export const HEROES: Hero[] = [
    { id: 1, name: 'Momo', property: 'rock', type: 'Attack' },
    { id: 2, name: 'Mu', property: 'paper', type: 'Balance' },
    { id: 3, name: 'Carrot', property: 'paper', type: 'Attack' },
    { id: 4, name: 'Deborah', property: 'scissors', type: 'AreaAttack' },
    { id: 5, name: 'Kai', property: 'rock', type: 'Balance' },
    { id: 6, name: 'Alfred', property: 'rock', type: 'AreaAttack' },
    { id: 7, name: 'Lance', property: 'scissors', type: 'Defense' },
    { id: 8, name: 'Mas', property: 'paper', type: 'Support' },
    { id: 9, name: 'Ian', property: 'rock', type: 'Balance' },
    { id: 10, name: 'Sonic Boom', property: 'scissor', type: 'Balance' },
    { id: 11, name: 'Sraka', property: 'scissor', type: 'Attack' },
    { id: 12, name: 'Jack', property: 'rock', type: 'Defense' },
    { id: 13, name: 'Poni', property: 'scissor', type: 'Balance' },
    { id: 14, name: 'Rage', property: 'rock', type: 'Attack' },
    { id: 15, name: 'Serendi', property: 'rock', type: 'Balance' },
    { id: 16, name: 'Chris', property: 'paper', type: 'Defense' },
    { id: 17, name: 'Dolores', property: 'paper', type: 'Balance' },
    { id: 18, name: 'Jenny', property: 'paper', type: 'AreaAttack' },
    { id: 19, name: 'Gillan', property: 'rock', type: 'Support' },
    { id: 20, name: 'Jin', property: 'scissor', type: 'Attack' },
    { id: 21, name: 'Lily', property: 'paper', type: 'Attack' },
    { id: 22, name: 'Raboff', property: 'paper', type: 'Defense' },
    { id: 23, name: 'Dominique', property: 'rock', type: 'Attack' },
    { id: 24, name: 'Frankenstein', property: 'scissor', type: 'Attack' },
    { id: 25, name: 'Raskreia', property: 'scissor', type: 'AreaAttack' },
    { id: 26, name: 'Cleo', property: 'paper', type: 'Balance' },
    { id: 27, name: 'Valkyrie', property: 'paper', type: 'Defense' },
    { id: 28, name: 'Bearman', property: 'scissor', type: 'Defense' },
    { id: 29, name: 'Moa', property: 'paper', type: 'AreaAttack' },
    { id: 30, name: 'Lilid', property: 'rock', type: 'Defense' },
    { id: 31, name: 'Alex', property: 'paper', type: 'Balance' },
    { id: 32, name: 'Kitty', property: 'rock', type: 'AreaAttack' },
    { id: 33, name: 'Persona', property: 'rock', type: 'Balance' },
    { id: 34, name: 'Henry', property: 'rock', type: 'Attack' },
    { id: 35, name: 'Tao', property: 'scissor', type: 'Attack' },
    { id: 36, name: 'Shark', property: 'scissor', type: 'Balance' },
    { id: 37, name: 'Muang', property: 'scissor', type: 'AreaAttack' },
    { id: 38, name: 'Spooky', property: 'rock', type: 'Support' },
    { id: 39, name: 'Shu- Shu', property: 'rock', type: 'Support' },
    { id: 40, name: 'Banshee', property: 'scissor', type: 'Balance' },
    { id: 41, name: 'Unknown', property: 'rock', type: 'Attack' },
    { id: 42, name: 'Chenny', property: 'scissor', type: 'Balance' },
    { id: 43, name: 'Krut', property: 'rock', type: 'Attack' },
    { id: 44, name: 'Lena', property: 'scissor', type: 'Balance' },
    { id: 45, name: 'Nox', property: 'paper', type: 'Attack' },
    { id: 46, name: 'Zero', property: 'rock', type: 'Balance' },
    { id: 47, name: 'Nirvana', property: 'paper', type: 'Support' },
    { id: 48, name: 'Fruel', property: 'scissor', type: 'Attack' },
    { id: 49, name: 'Lucas', property: 'paper', type: 'Balance' },
    { id: 50, name: 'Celestial', property: 'paper', type: 'Support' },
    { id: 51, name: 'Ragna', property: 'scissor', type: 'Attack' },
    { id: 52, name: 'Noel', property: 'rock', type: 'Attack' },
    { id: 53, name: 'Rachel', property: 'paper', type: 'AreaAttack' },
    { id: 54, name: 'Elektra', property: 'scissor', type: 'Support' },
    { id: 55, name: 'Belle', property: 'scissor', type: 'Support' },
    { id: 56, name: 'Phantom', property: 'paper', type: 'Balance' },
    { id: 57, name: 'Evan', property: 'scissor', type: 'AreaAttack' },
    { id: 58, name: 'Mercedes', property: 'rock', type: 'Attack' },
    { id: 59, name: 'Deimos', property: 'scissor', type: 'Defense' },
    { id: 60, name: 'Angela', property: 'paper', type: 'Balance' },
    { id: 61, name: 'Reina', property: 'scissor', type: 'Balance' },
    { id: 62, name: 'Luminous', property: 'scissor', type: 'Support' },
    { id: 63, name: 'Aran', property: 'rock', type: 'Balance' },
    { id: 64, name: 'Cat Sidhe', property: 'rock', type: 'Attack' },
    { id: 65, name: 'Sephina', property: 'scissor', type: 'AreaAttack' },
    { id: 66, name: 'Thanatos', property: 'rock', type: 'Balance' },
    { id: 67, name: 'Lee', property: 'scissor', type: 'Attack' },
    { id: 68, name: 'Azrael', property: 'paper', type: 'Attack' },
    { id: 69, name: 'Klein', property: 'paper', type: 'AreaAttack' },
    { id: 70, name: 'Sione', property: 'scissor', type: 'Attack' },
    { id: 71, name: 'Ildo', property: 'paper', type: 'Defense' },
    { id: 72, name: 'Hongyeom', property: 'rock', type: 'AreaAttack' },
    { id: 73, name: 'Sol Badguy', property: 'rock', type: 'Balance' },
    { id: 74, name: 'Yeka', property: 'rock', type: 'Balance' },
    { id: 75, name: 'Taehwa', property: 'scissor', type: 'Balance' },
    { id: 76, name: 'Camelia', property: 'paper', type: 'Support' },
    { id: 77, name: 'Ramlethal Valentine', property: 'scissor', type: 'AreaAttack' },
    { id: 78, name: 'May', property: 'scissor', type: 'Attack' }
];